### ISSUE TITLE
Merge conflict detritus in paper "Technical Dimensions of Programming Systems"

### ISSUE THREAD

**Issue by ristew** [jdjakub/papers#1]
Noticed a familiar sight while reading the paper, on page 14.

https://github.com/jdjakub/papers/blob/master/prog-2022/prog22-manuscript.md#-updated-upstreammyboxhow-do-users-manifest-their-ideas-evaluate-the-result-and-generate-new-ideas-in-response

**Comment by jdjakub** [comment]
Oops. I think I forgot to push a commit which included getting rid of this. Should be fixed now, thanks
